
package:
  name: quetz_sql_authenticator
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}{% if environ.get('GIT_DESCRIBE_NUMBER', 0)|int != 0 %}.post{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}{% endif %}

source:
  git_url: ../


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv --no-build-isolation --disable-pip-version-check"


requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - quetz =0.4.4
    - sqlalchemy
    - fastapi
    - alembic
    - passlib

test:
  requires:
    - pip
    - pytest>=6
    - pytest-cov
    - pytest-mock
  commands:
    - pip check
  imports:
    - quetz_sql_authenticator

about:
  home: https://github.com/mamba-org/quetz-sql-authenticator
  license: Proprietary
